blank_issues_enabled: true
contact_links:
  - name: Help
    url: https://discord.com/invite/kcriff
    about: Please join our Discord server for help using kcriff
  - name: Troubleshooting
    url: https://github.com/sbug51/kc-riff/blob/main/docs/faq.md#faq
    about: See the FAQ for common issues and solutions
